# Values for Staging environment
replicaCount: 2

image:
  tag: "main"

ingress:
  enabled: true
  hosts:
    - host: api.staging.nexo.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexo-be-staging-tls
      hosts:
        - api.staging.nexo.io

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

env:
  NODE_ENV: staging
  LOG_LEVEL: info
  SWAGGER_ENABLED: "false"
  METRICS_ENABLED: "true"
  KEYCLOAK_REALM: nexo-staging

podDisruptionBudget:
  enabled: true
  minAvailable: 1
