# Values for QA environment
replicaCount: 1
image:
  repository: ghcr.io/geraldobl58/nexo-be
  tag: "qa-04a0f66f000ab517c72a4152ab7a6c91f72a99aa"
  pullPolicy: Always
imagePullSecrets:
  - name: dockerhub-secret
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: qa.api.nexo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
env:
  NODE_ENV: qa
  LOG_LEVEL: info
  SWAGGER_ENABLED: "true"
  METRICS_ENABLED: "true"
  KEYCLOAK_REALM: nexo-qa
envFrom: []
podDisruptionBudget:
  enabled: false
podAnnotations:
  app.kubernetes.io/commit: "04a0f66"
