# Values for QA environment
# Deploy autom√°tico via branch 'qa'
replicaCount: 1

image:
  repository: docker.io/geraldobl58/nexo-be
  tag: "qa"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.qa.nexo.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexo-be-qa-tls
      hosts:
        - api.qa.nexo.io

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  NODE_ENV: qa
  LOG_LEVEL: info
  SWAGGER_ENABLED: "true"
  METRICS_ENABLED: "true"
  KEYCLOAK_REALM: nexo-qa

# Para ambiente local, sem secrets externos
envFrom: []

podDisruptionBudget:
  enabled: false
