# Values for Development environment
replicaCount: 1
image:
  # Para desenvolvimento local com K3D
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "develop-6dfc569a856f696d95f2c2ccd58c43ddea002eb7"
  pullPolicy: Always
# Para ambientes remotos, usar dockerhub-secret
# Para K3D local, deixar vazio
# imagePullSecrets: (n√£o precisa para registry local)
#   - name: ghcr-secret
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: nexo-fe.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
env:
  NODE_ENV: development
  NEXT_PUBLIC_API_URL: http://nexo-be.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://nexo-auth.local
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo-dev
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-fe
podDisruptionBudget:
  enabled: false
podAnnotations:
  app.kubernetes.io/commit: "6dfc569"
