# Values for Staging environment
# Deploy autom√°tico via branch 'staging'
replicaCount: 2

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "staging-233cbb13f2068435df38e91ccea2aca85329a6fd"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: staging.nexo.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexo-fe-staging-tls
      hosts:
        - staging.nexo.local

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

env:
  NODE_ENV: staging
  NEXT_PUBLIC_API_URL: https://api.staging.nexo.local
  NEXT_PUBLIC_KEYCLOAK_URL: https://auth.staging.nexo.local
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo-staging
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-fe

# Para ambiente local, sem secrets externos
envFrom: []

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations:
  app.kubernetes.io/commit: "233cbb1"
