# Values for Staging environment
# Deploy autom√°tico via branch 'staging'
replicaCount: 2

image:
  repository: docker.io/geraldobl58/nexo-fe
  tag: "staging"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: staging.nexo.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexo-fe-staging-tls
      hosts:
        - staging.nexo.io

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

env:
  NODE_ENV: staging
  NEXT_PUBLIC_API_URL: https://api.staging.nexo.io
  NEXT_PUBLIC_KEYCLOAK_URL: https://auth.staging.nexo.io
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo-staging
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-fe

# Para ambiente local, sem secrets externos
envFrom: []

podDisruptionBudget:
  enabled: true
  minAvailable: 1
